pub fn description(&self) -> &'static str {
    match self {
        Self::V0 | Self::V1 | Self::V2 | Self::V3 => "按键传入的参数/通用寄存器",
        Self::R0 | Self::R1 | Self::R2 | Self::R3 | Self::R4 | Self::R5 | Self::R6 | Self::R7 |
        Self::R8 | Self::R9 | Self::R10 | Self::R11 | Self::R12 | Self::R13 | Self::R14 | Self::R15 => "通用寄存器",
        Self::DPTR => "映射到 R4",
        Self::StarDPTR => "ROM寻址专用寄存器，映射到 R4，共享地址空间",
        Self::KeyIO => "0=pressed",
        Self::StarR0 | Self::StarR1 | Self::StarR2 | Self::StarR3 => "使用寄存器寻址RAM（8位）",
        Self::StarR4 | Self::StarR5 | Self::StarR6 | Self::StarR7 => "使用寄存器寻址RAM（8位）",
        Self::StarR0_16b | Self::StarR1_16b | Self::StarR2_16b | Self::StarR3_16b |
        Self::StarR4_16b | Self::StarR5_16b | Self::StarR6_16b | Self::StarR7_16b => "使用寄存器寻址RAM（16位）",
        Self::StarR0_32b | Self::StarR1_32b | Self::StarR2_32b | Self::StarR3_32b |
        Self::StarR4_32b | Self::StarR5_32b | Self::StarR6_32b | Self::StarR7_32b => "使用寄存器寻址RAM（32位）",
        Self::Zero => "读取恒为0",
        Self::A => "专用寄存器。映射到R6，共享地址空间。某些指令可以用此寄存器可以减少代码长度",
        Self::B => "专用寄存器。映射到R7，共享地址空间。某些指令可以用此寄存器可以减少代码长度",
        Self::SysTimeMs => "系统时间，毫秒。取值范围0~999",
        Self::SysTimeS => "系统时间，秒。",
        Self::SysKbled => "键盘 LED 状态（Num Lock、Caps Lock、Scroll Lock等）",
        Self::SysKeyCount => "系统物理按键次数计数",
        Self::SysKeyLay => "键盘层级。一个键盘可能有多层按键设置",
        Self::ScriptAddr => "脚本起始地址",
        Self::Random => "R:获取随机数 W:设置随机数种子",
        Self::SysBleNum => "蓝牙多机切换",
        Self::SysVolume => "绝对系统音量；因windows系统无效目前无作用",
        Self::SelectedLed => "选中操作的LED灯。默认选中执行按键本身的LED",
        Self::SelectedLedCol => "修改选中灯的灯光颜色（RGB888）",
        Self::AllLedCol => "修改全部灯的灯光颜色（RGB888）",
        Self::CfgAddr => "获取当前配置文件地址",
        Self::HeKeyLv => "磁轴的按键深度数值，单位um",
        Self::SysUsbSusp => "R：1=USB处于休眠状态 W：唤醒主机",
        Self::GlSize => "有多少个GL寄存器(至少有4个，最多有64个)",
        Self::Gl(_) => "通用全局寄存器",
    }
}



pub fn description(&self) -> (&'static str, &'static str) {
    // Returns (description, note)
    match self {
        Self::END => ("程序结束", ""),
        Self::NOP => ("空操作", ""),
        Self::JMP => ("PC = i;", "长跳转"),
        Self::SJMP => ("PC = PC + i;", "短跳转，偏移量"),
        Self::AJMP => ("PC = (PC & 0xff00) + i;", "在地址的256B范围内跳转"),
        Self::SLEEP_X256 => ("Sleep(i * 256);", "延时范围0-65280ms（256倍率）"),
        Self::SLEEP => ("Sleep(i * 1);", "延时范围0-255ms"),
        Self::SLEEP_RAND_X256 => ("Sleep(rand()%(i * 256)+1);", "随机延时范围1-65281ms（256倍率）"),
        Self::SLEEP_RAND => ("Sleep(rand()%i+1);", "随机延时范围1-256ms"),
        Self::SLEEP_X256_VAL => ("Sleep(i * 256);", "延时的寄存器版本，范围取决于寄存器（256倍率）"),
        Self::SLEEP_VAL => ("Sleep(i);", "延时的寄存器版本，范围取决于寄存器"),
        Self::SLEEP_RAND_X8_VAL => ("Sleep(rand()%(i * 8)+1);", "随机延时的寄存器版本，范围取决于寄存器（8倍率）"),
        Self::SLEEP_RAND_VAL => ("Sleep(rand()%i+1);", "随机延时的寄存器版本，范围取决于寄存器"),
        Self::SLEEP_U16 => ("Sleep(i);", "延时范围1-65536ms"),
        Self::SLEEP_RAND_U16 => ("Sleep(rand()%i+1);", "延时范围1-65536ms"),
        Self::PRESS_SK => ("键盘 修饰键 i 按下", "HID键码"),
        Self::PRESS_GK => ("键盘 普通键 i 按下", "HID键码"),
        Self::PRESS_MK => ("鼠标 鼠标键 i 按下", "HID键码"),
        Self::PRESS_MU => ("按键 多媒体 i 按下", "HID键码"),
        Self::RELEASE_SK => ("键盘 修饰键 i 释放", "HID键码"),
        Self::RELEASE_GK => ("键盘 普通键 i 释放", "HID键码"),
        Self::RELEASE_MK => ("鼠标 鼠标键 i 释放", "HID键码"),
        Self::RELEASE_MU => ("按键 多媒体 i 释放", "HID键码"),
        Self::MOV => ("i=j;", ""),
        Self::MOV8 => ("i=j;", "8位宽度"),
        Self::MOV16 => ("i=j;", "16位宽度"),
        Self::MOV32 => ("i=j;", "32位宽度"),
        Self::ADD => ("i=i+j;", ""),
        Self::ADD8 => ("i=i+j;", "8位宽度"),
        Self::ADD16 => ("i=i+j;", "16位宽度"),
        Self::ADD32 => ("i=i+j;", "32位宽度"),
        Self::SUB => ("i=i-j;", ""),
        Self::SUB8 => ("i=i-j;", "8位宽度"),
        Self::SUB16 => ("i=i-j;", "16位宽度"),
        Self::SUB32 => ("i=i-j;", "32位宽度"),
        Self::AND => ("i=i&j;", "按位与"),
        Self::AND8 => ("i=i&j;", "8位宽度"),
        Self::AND16 => ("i=i&j;", "16位宽度"),
        Self::AND32 => ("i=i&j;", "32位宽度"),
        Self::OR => ("i=i|j;", "按位或"),
        Self::OR8 => ("i=i|j;", "8位宽度"),
        Self::OR16 => ("i=i|j;", "16位宽度"),
        Self::OR32 => ("i=i|j;", "32位宽度"),
        Self::XOR => ("i=i^j;", "按位异或"),
        Self::XOR8 => ("i=i^j;", "8位宽度"),
        Self::XOR16 => ("i=i^j;", "16位宽度"),
        Self::XOR32 => ("i=i^j;", "32位宽度"),
        Self::CALL => ("PUSH PC;PC=i;", "调用子程序，目标地址为label"),
        Self::RET => ("POP PC;", "子程序返回"),
        Self::PUSH => ("", "压栈"),
        Self::POP => ("", "出栈"),
        Self::JZ => ("if (!i) PC = j;", "寄存器为0跳转。目标地址为label"),
        Self::JNZ => ("if (i) PC = j;", "寄存器不为0跳转。目标地址为label"),
        Self::DEC => ("i--;", "减一"),
        Self::INC => ("i++;", "加一"),
        Self::CLR => ("i=0;", "寄存器清零"),
        Self::NOT => ("i=~i;", "寄存器按位取反"),
        Self::CMP => ("CY=i<j;", "比较两个寄存器并设置CY标识"),
        Self::ADD_R => ("i=j+k;", "三操作数加法"),
        Self::SUB_R => ("i=j-k;", "三操作数减法"),
        Self::AND_R => ("i=j&k;", "三操作数按位与"),
        Self::OR_R => ("i=j|k;", "三操作数按位或"),
        Self::XOR_R => ("i=j^k;", "三操作数按位异或"),
        Self::MUL_R => ("i=j*k;", "三操作数乘法"),
        Self::DIV_R => ("i=j/k;", "三操作数除法"),
        Self::MOD_R => ("i=j%k;", "三操作数取模"),
        Self::NEW_THREAD => ("i=TH ID;j=addr or keymode;k=V[4]", "i的取值范围0~3"),
        Self::LED_CTRL => ("SELECTED_LED = i;", "0xff = release"),
        Self::EXIT => ("exit();", "退出脚本"),
        Self::UPDATE => ("HID数据包强制重传", "一般不会使用"),
        Self::KEY_TO_AXIS => ("joystick axis=reg::val[0] type=reg::val[1]", "内部使用"),
        Self::C2K => ("print ascii character", "内部使用"),
        Self::U2K => ("print unicode character", "内部使用"),
        Self::C2K_RAND => ("print random ascii character", "内部使用"),
        Self::U2K_REG => ("print value", "内部使用，需要循环调用直到输出完毕"),
        Self::MUL_A => ("A = A * B;", "乘法，结果存入A"),
        Self::DIV_A => ("A = A / B;B = A % B;", "除法，商存入A，余数存入B"),
        Self::IMUL_A => ("A=A*B;", "有符号乘法，结果存入A"),
        Self::WHILE_UPDATE => ("while (update_flag)Sleep(1);", "等待HID上传数据完成"),
        Self::MODE_JOG => ("", "进入点动模式（再次按下按键不会被强制打断）"),
        Self::WAIT_IF_RELEASE => ("while (IO) Sleep(1);", "如果物理按键是释放状态，等待按下后才会继续执行"),
        Self::WAIT_IF_PRESS => ("while (!IO) Sleep(1);", "如果物理按键是按下状态，等待释放后才会继续执行"),
        Self::EXIT_IF_RELEAS => ("if (IO) exit();", "如果物理按键是释放的，退出脚本"),
        Self::EXIT_IF_PRESS => ("if (!IO) exit();", "如果物理按键是按下的，退出脚本"),
        Self::EXIT_IF_ANYKEY => ("if (SYS_KEY_COUNT != n) exit();", "n=脚本开始执行时保存的按键计数器。脚本执行后，可以用此指令实现按任意键退出"),
        Self::RES => ("PC = 0;", "跳转到程序开头，等同于JMP 0"),
        Self::XCH => ("i <=> j;", "交换两个寄存器的值"),
        Self::SHL => ("i=i<<j;", "逻辑左移"),
        Self::SHL8 => ("i=i<<j;", "8位立即数"),
        Self::SHR => ("i=i>>j;", "逻辑右移"),
        Self::SHR8 => ("i=i>>j;", "8位立即数"),
        Self::JC => ("if (CY) PC = i;", "如果CY置位，则跳转。目标地址为label"),
        Self::JNC => ("if (!CY) PC = i;", "如果CY没有置位，则跳转。目标地址为label"),
        Self::JFC => ("if (CY) PC = i;", "如果CY置位，则跳转。目标地址存储于寄存器"),
        Self::JFNC => ("if (!CY) PC = i;", "如果CY没有置位，则跳转。目标地址存储于寄存器"),
        Self::PRESS_SK_VAL => ("键盘 修饰键 i 按下", "寄存器版本"),
        Self::PRESS_GK_VAL => ("键盘 普通键 i 按下", "寄存器版本"),
        Self::PRESS_MK_VAL => ("鼠标 鼠标键 i 按下", "寄存器版本"),
        Self::PRESS_MU_VAL => ("按键 多媒体 i 按下", "寄存器版本"),
        Self::RELEASE_SK_VAL => ("键盘 修饰键 i 释放", "寄存器版本"),
        Self::RELEASE_GK_VAL => ("键盘 普通键 i 释放", "寄存器版本"),
        Self::RELEASE_MK_VAL => ("鼠标 鼠标键 i 释放", "寄存器版本"),
        Self::RELEASE_MU_VAL => ("按键 多媒体 i 释放", "寄存器版本"),
        Self::PRESS_GAK => ("joystick 按键 i 按下", ""),
        Self::PRESS_GAK_VAL => ("joystick 按键 i 按下", "寄存器版本"),
        Self::RELEASE_GAK => ("joystick 按键 i 释放", ""),
        Self::RELEASE_GAK_VAL => ("joystick 按键 i 释放", "寄存器版本"),
        Self::DIAL_DATA => ("Dial data=i", "data:0=release 1=press 2=cw 3=ccw"),
        Self::DIAL_DATA_VAL => ("Dial data=i", "data:0=release 1=press 2=cw 3=ccw，寄存器版本"),
        Self::PRINT_REG => ("print value", "打印寄存器值，只需要执行一次即可完整输出"),
        Self::START => ("Start_key(i-1);", "0=all"),
        Self::STOP => ("Stop_key(i-1);", "0=all"),
        Self::SYCON => ("", "系统控制"),
        Self::JMP_TO_SCRIPT => ("", "跳转到其他脚本号（寄存器数据保留，但PC会重置）"),
        Self::MALLOC => ("i=malloc(i);", ""),
        Self::FREE => ("i=free(i);", ""),
        Self::MOV_PC2REG => ("i=PC;", "把下一条指令的地址保存到寄存器"),
        Self::VALUE_RELOAD => ("i=Reload(reg);", "重新加载脚本参数"),
        Self::MO_XYZ => ("鼠标 光标移动 axis=i data=j", "0: x, 1:y, 2:scroll"),
        Self::MO_XYZ_VAL => ("鼠标 光标移动 axis=i data=j", "寄存器版本"),
        Self::GA_XYZ => ("joystick axis=i data=j", ""),
        Self::GA_XYZ_VAL => ("joystick axis=i data=j", "寄存器版本"),
        Self::TB_XY => ("鼠标 光标定位 x=i y=j", ""),
        Self::TB_XY_VAL => ("鼠标 光标定位 x=i y=j", "寄存器版本"),
        Self::JFZ => ("if (!i) PC = j;", "寄存器为0跳转。目标地址存储于寄存器"),
        Self::JFNZ => ("if (i) PC = j;", "寄存器不为0跳转。目标地址存储于寄存器"),
        Self::DJFNZ => ("if (--i) PC = j;", "寄存器减1并存回，寄存器不为0跳转。目标地址存储于寄存器"),
        Self::DJNZ => ("if (--i) PC = j;", "寄存器减1并存回，寄存器不为0跳转。目标地址为label"),
        Self::JFA => ("if (i>j)PC=k;", "比较两个寄存器的值(无符号数)，根据结果判断是否跳转，目标地址存储于寄存器"),
        Self::JFB => ("if (i<j)PC=k;", "比较两个寄存器的值(无符号数)，根据结果判断是否跳转，目标地址存储于寄存器"),
        Self::JFG => ("if (i>j)PC=k;", "比较两个寄存器的值(无符号数)，根据结果判断是否跳转，目标地址存储于寄存器"),
        Self::JFL => ("if (i<j)PC=k;", "比较两个寄存器的值(无符号数)，根据结果判断是否跳转，目标地址存储于寄存器"),
        Self::CJFNE => ("if (i != j) {CY = i<j;PC = k}", "比较两个寄存器并设置CY标识，不相等则跳转。目标地址存储于寄存器"),
        Self::JA => ("if (i>j)PC=k;", "比较两个寄存器的值(有符号数)，根据结果判断是否跳转，目标地址为label"),
        Self::JB => ("if (i<j)PC=k;", "比较两个寄存器的值(有符号数)，根据结果判断是否跳转，目标地址为label"),
        Self::JG => ("if (i>j)PC=k;", "比较两个寄存器的值(有符号数)，根据结果判断是否跳转，目标地址为label"),
        Self::JL => ("if (i<j)PC=k;", "比较两个寄存器的值(有符号数)，根据结果判断是否跳转，目标地址为label"),
        Self::CJNE => ("if (i != j) {CY = i<j;PC = k}", "比较两个寄存器并设置CY标识，不相等则跳转。目标地址为label"),
        Self::LED_COL => ("SELECTED_LED_COL = i;", "RGB888格式"),
        Self::MOVSX8b => ("i = sign_extend(j);", "8位符号扩展到目标位宽"),
        Self::MOVSX16b => ("i = sign_extend(j);", "16位符号扩展到目标位宽"),
        Self::MOV8SX => ("i = sign_extend(imm8);", "8位立即数符号扩展"),
        Self::MOV16SX => ("i = sign_extend(imm16);", "16位立即数符号扩展"),
        Self::IMUL_R => ("i=j*k;", "三操作数有符号乘法"),
        Self::ADD_A => ("A = A + i;", "加到A寄存器"),
        Self::SUB_A => ("A = A - i;", "从A寄存器减"),
        Self::OR_A => ("A = A | i;", "按位或到A寄存器"),
        Self::ADD8_A => ("A = A + i;", "8位立即数加到A"),
        Self::SUB8_A => ("A = A - i;", "8位立即数从A减"),
        Self::OR8_A => ("A = A | i;", "8位立即数按位或到A"),
    }
}
